stproject/credentials/urls.py
from django.urls import path

from . import views
app_name = 'credentials'
# here we going to views using path and function
urlpatterns = [

    path('register/', views.register, name='rregister'),
    path('login/',views.login,name='rlogin'),
    path('logout/',views.logout,name='rlogout'),
]

stproject/stapp/urls.py
from django.urls import path
from .import views

app_name = 'stapp'

urlpatterns = [
    path('',views.allCourseDept,name='allcat'),
    path('studentreg/',views.studentreg,name='form'),
    path('coursedetails/',views.coursedet,name='rcourse'),
    path('get_courses_by_department/<int:department_id>/', views.get_courses_by_department, name='get_courses_by_department'),
    path('touch/',views.getintouch,name='rtouch'),
    ]

stproject/stproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("stapp.urls")),
    path('credentials/',include("credentials.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

stproject/credentials/models.py
from django.db import models

# Create your models here.

stproject/stapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Department(models.Model):
    objects = None
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='Product', blank=True)

    class Meta:
        ordering=('name', )
        verbose_name='Department'
        verbose_name_plural='Departments'

    def get_url(self):
        return reverse('stap:allcat', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Course(models.Model):

    objects = None
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    fees=models.DecimalField(max_digits=10,decimal_places=2)
    department=models.ForeignKey(Department,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='Product',blank=True)
    no_of_seats=models.IntegerField()
    # purpose=models.TextField(blank=True)

    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    # def get_url(self):
    #     return reverse('stapp:course_by_dept',args=[self.department.slug,self.slug])

    class Meta:
        ordering=('name', )
        verbose_name='Course'
        verbose_name_plural='Courses'



    def __str__(self):
        return '{}'.format(self.name)

stproject/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse


# Create your views here.


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        fullname = request.POST['fullname']
        phonenumber=request.POST['phno']
        email = request.POST['email']
        password1 = request.POST['password']
        password2 = request.POST['password1']
        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username alreary Exists")
                return redirect('register')

            elif User.objects.filter(email=email).exists():
                messages.info(request, "email already Exists")
                return redirect('register')

            else:
                user = User.objects.create_user(username=username, password=password1,email=email)
                user.save()

                print("user created")
                return redirect('login')


        else:
            messages.info(request, "password not matching")
            return redirect('register')

    return render(request, "register.html")


def login(request):
    if request.method== 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, "invalid credentials")
            return redirect('credentials:rlogin')

    return render(request, "login.html")


def logout(request):
    auth.logout(request)
    return redirect('/')

stproject/stapp/views.py
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from stapp.models import Department,Course




def allCourseDept(request):
    depts = Department.objects.all()
    courses =Course.objects.all()
    return render(request, 'index.html', {'depts':depts, 'courses':courses})


from django.shortcuts import render
from .models import Department, Course

def studentreg(request):
    departments = Department.objects.distinct().order_by('name')
    return render(request, 'form.html', {'departments': departments})


def get_courses_by_department(request, department_id):
    courses = Course.objects.filter(department_id=department_id).values('id', 'name')
    return JsonResponse(list(courses), safe=False)

def coursedet(request):
    depts = Department.objects.all()
    courses =Course.objects.all()
    return render(request, 'course.html', {'depts':depts, 'courses':courses})


def getintouch(request):
    return render(request, 'getintouch.html')

stproject/templates/course.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Template Mo">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <title>Education - List of Meetings</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-edu-meeting.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'css/lightbox.css' %}">
</head>
<body>

<!-- Sub Header -->
<div class="sub-header">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-sm-8">
          <div class="left-content">
            <p>Education-focused website for learning by StraightPath</p>
          </div>
        </div>
        <div class="col-lg-4 col-sm-4">
          <div class="right-icons">
            <ul>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-behance"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="index.html" class="logo">
                        <div class="icon">
                            <a href="{% url 'stapp:allcat' %}">
                              <img  src="{% static 'images/stlogo.png' %}" alt="Logo" style="max-height: 200px; max-width: 200px; float: left;">
                            </a>
                        </div>


                    <a href="index.html" class="logo">Straight Path University</a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li><a href="{% url 'stapp:allcat' %}">Home</a></li>

                        <li><a href="{% url 'stapp:form' %}">Apply Now</a></li>

                    </ul>
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ***** Header Area End ***** -->

<section class="heading-page header-text" id="top">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h6>Here are our upcoming meetings</h6>
                <h2>Upcoming Meetings</h2>
            </div>
        </div>
    </div>
</section>

<section class="meetings-page" id="meetings">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row grid">
                            {% for course in courses %}
                            <div class="col-lg-4 templatemo-item-col all soon">
                                <div class="meeting-item">
                                    <div class="thumb">
                                        <div class="price">
                                            <span>${{course.fees}}</span>
                                        </div>
                                        <a href="https://en.wikipedia.org/wiki/{{course.name}}">
                                            <img src="{{course.image.url}}" alt="{{course.name}}">
                                        </a>
                                    </div>
                                    <div class="down-content">
<!--                                        <div class="date">-->
<!--                                            <h6>Nov <span>12</span></h6>-->
<!--                                        </div>-->
                                        <a href="https://en.wikipedia.org/wiki/{{course.name}}"><h4>{{course.name}}</h4></a>
                                        <p>{{course.description}}</p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="footer">
      <p>Copyright © 2022 Edu Meeting Co., Ltd. All Rights Reserved.
          <br>Design: AMK Developers PVT LTD</p>
    </div>

<!-- Scripts -->
<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/js/isotope.min.js' %}"></script>
<script src="{% static 'assets/js/owl-carousel.js' %}"></script>
<script src="{% static 'assets/js/lightbox.js' %}"></script>
<script src="{% static 'assets/js/tabs.js' %}"></script>
<script src="{% static 'assets/js/isotope.js' %}"></script>
<script src="{% static 'assets/js/video.js' %}"></script>
<script src="{% static 'assets/js/slick-slider.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
<script>
    //according to loftblog tut
    $('.nav li:first').addClass('active');

    var showSection = function showSection(section, isAnimate) {
      var
      direction = section.replace(/#/, ''),
      reqSection = $('.section').filter('[data-section="' + direction + '"]'),
      reqSectionPos = reqSection.offset().top - 0;

      if (isAnimate) {
        $('body, html').animate({
          scrollTop: reqSectionPos },
        800);
      } else {
        $('body, html').scrollTop(reqSectionPos);
      }
    };

    var checkSection = function checkSection() {
      $('.section').each(function () {
        var
        $this = $(this),
        topEdge = $this.offset().top - 80,
        bottomEdge = topEdge + $this.height(),
        wScroll = $(window).scrollTop();
        if (topEdge < wScroll && bottomEdge > wScroll) {
          var
          currentId = $this.data('section'),
          reqLink = $('a').filter('[href*=\\#' + currentId + ']');
          reqLink.closest('li').addClass('active').
          siblings().removeClass('active');
        }
      });
    };

    $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {
      e.preventDefault();
      showSection($(this).attr('href'), true);
    });

    $(window).scroll(function () {
      checkSection();
    });
</script>
</body>
</html>

stproject/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
    <title>Free Online Student Registration Form</title>
</head>

<body>
    <div class="container">
        <h1>STRAIGHT PATH UNIVERSITY</h1>
        <h2>Student Registration Form</h2>
        <div class="form-wrapper">
            <form action="">
                <div class="form-item">
                    <label for="studentimage">Student Image:</label>
                    <input type="file" name="studentimage" id="studentimage" required>
                    <p>(less than 5 Mb)</p>
                </div>
                <div class="form-item">
                    <label for="fullname">Student Name:</label>
                    <input type="text" name="fullname" id="fullname" placeholder="Full Name" required>
                </div>
                <div class="form-item">
                    <label for="fathersname">Father's Name:</label>
                    <input type="text" name="fathersname" id="fathersname" placeholder="Father's Full Name" required>
                </div>
                <div class="form-item">
                    <label for="mothersname">Mother's Name:</label>
                    <input type="text" name="mothersname" id="mothersname" placeholder="Mother's Full Name" required>
                </div>
                <div class="form-item">
                    <label for="gender">Gender:</label>
                    <div class="genders">
                        <p>Male</p> <input type="radio" name="gender" id="gender" value="male" required>
                        <p>Female</p> <input type="radio" name="gender" id="gender" value="female">
                        <p>Other</p> <input type="radio" name="gender" id="gender" value="other">
                    </div>
                </div>
                <div class="form-item">
                    <label for="email">Date of Birth:</label>
                    <input type="date" name="DOB" id="DOB" required>
                </div>
                <div class="form-item">
                    <label for="age">Age:</label>
                    <input type="number" name="age" id="age" placeholder="Age" required>
                </div>
                <div class="form-item">
                    <label for="email">E-mail:</label>
                    <input type="email" name="email" id="email" placeholder="email@xyz.com" required>
                </div>
                <div class="form-item">
                    <label for="phonenumber">Tel/Mobile:</label>
                    <input type="tel" name="phonenumber" id="phonenumber" placeholder="XXX XXX XXXX" required>
                </div>
                <div class="form-item">
                    <label for="department">Department:</label>
                    <select id="department" name="department">
                        <option value="" disabled selected>Select a Department</option>
                        {% for department in departments %}
                        <option value="{{ department.id }}">{{ department.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-item">
                    <label for="course">Courses:</label>
                    <select id="course" name="course" disabled>
                        <option value="" disabled selected>Select a Department first</option>
                    </select>
                </div>
                <div class="form-item">
                    <label for="purpose">Purpose:</label>
                    <select name="purpose" id="purpose">
                        <option value="enquiry">Enquiry</option>
                        <option value="admission">Admission</option>
                        <!-- <option value="examtimetable">Exam TimeTable</option> -->
                        <option value="notifications">Notifications</option>
                    </select>
                </div>
                <div class="form-item">
                    <label>Materials Provided:</label>
                    <div class="materials">
                        <div style="display: inline-block;text-align: center;">
                        <input type="checkbox" id="material1" name="materials" value="Notebook">
                        <label for="material1">Study Materials</label>
                        </div>
                        <div style="display: inline-block;text-align: center;">
                        <input type="checkbox" id="material2" name="materials" value="Pen">
                        <label for="material2">Laptop</label>
                        </div>
                        <div style="display: inline-block;text-align: center;">
                        <input type="checkbox" id="material3" name="materials" value="Exam Papers">
                        <label for="material3">Assignment set</label>
                        </div>
                        <div style="display: inline-block;text-align: center;">
                        <input type="checkbox" id="material4" name="materials" value="Exam Papers">
                        <label for="material3">Laboratory Materials</label>
                        </div>

                        <!-- Add more materials with checkboxes as needed -->
                    </div>
                </div>

                <hr>
                <h3>Permanent Address</h3>
                <div class="form-item">
                    <label for="pstate">State:</label>
                    <input type="text" name="pstate" id="pstate" placeholder="State" required>
                </div>
                <div class="form-item">
                    <label for="pcity">City:</label>
                    <input type="text" name="pcity" id="pcity" placeholder="City" required>
                </div>
                <div class="form-item">
                    <label for="pzip">Zip Code:</label>
                    <input type="number" name="pzip" id="pzip" placeholder="Zip Code" required>
                </div>
                <div class="form-item">
                    <label for="pphonenumber">Tel/Mobile:</label>
                    <input type="tel" name="pphonenumber" id="pphonenumber" placeholder="XXX XXX XXXX" required>
                </div>
                <hr>
                <h3>Temporary Address</h3>
                <div class="same-perm">
                    <label for="sameaspermanent">Same as Permanent Address:</label> <input type="checkbox" name="sameaspermanent" id="sameaspermanent">
                </div>
                <div class="form-item">
                    <label for="tstate">State:</label>
                    <input type="text" name="tstate" id="tstate" placeholder="State" required>
                </div>
                <div class="form-item">
                    <label for="tcity">City:</label>
                    <input type="text" name="tcity" id="tcity" placeholder="City" required>
                </div>
                <div class="form-item">
                    <label for="tzip">Zip Code:</label>
                    <input type="number" name="tzip" id="tzip" placeholder="Zip Code" required>
                </div>
                <div class="form-item">
                    <label for="tphonenumber">Tel/Mobile:</label>
                    <input type="tel" name="tphonenumber" id="tphonenumber" placeholder="XXX XXX XXXX" required>
                </div>
                <button class="register" type="submit" id="confirmationButton">Submit</button>
                <button class="register" type="submit" id="confirmationButton2">Logout</button>
            </form>
            <script>
               var logoutURL = "{% url 'credentials:rlogout' %}";
               var submitURL = "{% url 'stapp:allcat' %}";

            </script>
            <script>

                // Get the button element by its id
                var button = document.getElementById("confirmationButton");

                // Add a click event listener to the button
                button.addEventListener("click", function () {
                    // Use the `confirm` function to display a confirmation dialog
                    var confirmed = confirm("Are you sure you want to proceed?");

                    // Check if the user confirmed or canceled
                    if (confirmed) {
                        alert("Confirmed! Proceeding...");
                        window.location.href = submitURL;
                    } else {
                        alert("Canceled.");
                    }
                });

                // Get the button element by its id
                var button2 = document.getElementById("confirmationButton2");

                // Add a click event listener to the button
                button2.addEventListener("click", function () {
                    // Use the `confirm` function to display a confirmation dialog
                    var confirmed = confirm("Do you want to logout");

                    // Check if the user confirmed or canceled
                    if (confirmed) {
                        alert("You are logging out....");
                        window.location.href = logoutURL;
                    } else {
                        alert("Continue editing....");
                    }
                });

                var departmentSelect = document.getElementById("department");
                var courseSelect = document.getElementById("course");

                departmentSelect.addEventListener("change", function () {
                    var selectedDepartmentId = departmentSelect.value;

                    // Clear course options
                    courseSelect.innerHTML = "";
                    courseSelect.disabled = true;

                    // Make an AJAX request to fetch courses based on the selected department
                    if (selectedDepartmentId) {
                        fetch(`/get_courses_by_department/${selectedDepartmentId}/`)
                            .then(response => response.json())
                            .then(data => {
                                courseSelect.innerHTML = '<option value="" disabled selected>Select a Course</option>';
                                data.forEach(course => {
                                    courseSelect.innerHTML += `<option value="${course.id}">${course.name}</option>`;
                                });
                                courseSelect.disabled = false; // Enable the course dropdown
                            })
                            .catch(error => {
                                console.error('Error fetching courses:', error);
                            });
                    } else {
                        // If no department is selected, disable the course dropdown
                        courseSelect.innerHTML = '<option value="" disabled selected>Select a Department first</option>';
                        courseSelect.disabled = true;
                    }
                });
            </script>
            <script src="{% static 'js/form.js' %}"></script>
        </div>
    </div>
</body>

</html>
<style>
body {
            background-image: url('{% static "images/meetings-page-bg.jpg" %}'); /* Replace 'your-background-image.jpg' with the path to your background image */

        }
</style>

stproject/templates/getintouch.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Notification</title>
    <style>
        body {
            background-image: url('{% static "images/meetings-bg.jpg" %}'); /* Replace 'your-background-image.jpg' with the path to your background image */
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: Arial, sans-serif;
            color: #fff;
            text-align: center;
        }

        .message {
            background-color: rgba(0, 0, 0, 0.7);
            padding: 20px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <div class="message">
        <h1>We will update through your mail</h1>
    </div>

    <div class="main-button-red">
        <a href="{% url 'stapp:allcat' %}">Home page</a>
    </div>
</body>
</html>

stproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<!-- Created By CodingLab - www.codinglabweb.com -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Login Form | CodingLab</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
  </head>
  <body>
    <div class="container">
      <div class="wrapper">
        <div class="title"><span>Login Form</span></div>
        <form method="post">
            {% csrf_token %}
          <div class="row">
            <i class="fas fa-user"></i>
            <input name="username" type="text" placeholder="username" required>
          </div>
          <div class="row">
            <i class="fas fa-lock"></i>
            <input name="password" type="password" placeholder="Password" required>
          </div>
<!--          <div class="pass"><a href="#">Forgot password?</a></div>-->
          <div class="row button">
            <input type="submit" value="Login">
          </div>
          <div class="signup-link">Not a member? <a href="/credentials/register/">Signup now</a></div>
        </form>
      </div>
    </div>

  </body>
</html>

stproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<!-- Designined by CodingLab - youtube.com/codinglabyt -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Responsive Registration Form | CodingLab </title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <div class="title">Registration</div>
    <div class="content">
      <form method="post">
        {% csrf_token %}
        <div class="user-details">
          <div class="input-box">
            <span class="details">Full Name</span>
            <input name="fullname" type="text" placeholder="Enter your name" required>
          </div>
          <div class="input-box">
            <span class="details">Username</span>
            <input name="username" type="text" placeholder="Enter your username" required>
          </div>
          <div class="input-box">
            <span class="details">Email</span>
            <input name="email" type="text" placeholder="Enter your email" required>
          </div>
          <div class="input-box">
            <span class="details">Phone Number</span>
            <input name="phno" type="text" placeholder="Enter your number" required>
          </div>
          <div class="input-box">
            <span class="details">Password</span>
            <input name="password" type="text" placeholder="Enter your password" required>
          </div>
          <div class="input-box">
            <span class="details">Confirm Password</span>
            <input name="password1" type="text" placeholder="Confirm your password" required>
          </div>
        </div>
        <div class="gender-details">
          <input type="radio" name="gender" id="dot-1">
          <input type="radio" name="gender" id="dot-2">
          <input type="radio" name="gender" id="dot-3">
          <span class="gender-title">Gender</span>
          <div class="category">
            <label for="dot-1">
            <span class="dot one"></span>
            <span class="gender">Male</span>
          </label>
          <label for="dot-2">
            <span class="dot two"></span>
            <span class="gender">Female</span>
          </label>
          <label for="dot-3">
            <span class="dot three"></span>
            <span class="gender">Prefer not to say</span>
            </label>
          </div>
        </div>
        <div class="button">
          <input type="submit" value="register">
          <div class="signup-link">Already having account? <a href="/credentials/login/">Login</a></div>
        </div>
      </form>
    </div>
  </div>

</body>
</html>